#!/usr/bin/env bash
set -e

### YALMIP
#
YALMIP_VER=R20181012
curl -sL https://github.com/yalmip/YALMIP/archive/$YALMIP_VER.tar.gz | tar xz
mv YALMIP-$YALMIP_VER YALMIP
echo 'Downloaded YALMIP'

### CVX
#
curl -sL http://web.cvxr.com/cvx/cvx-a64.tar.gz | tar zx
echo 'Downloaded CVX'

### SReachTools
#
git clone -n https://github.com/unm-hscl/SReachTools.git SReachTools
(cd SReachTools && git checkout 11bff8443d034b30c75b76171674171953d4424e)
echo 'Downloaded SReachTools'

### Setup MATLAB environment for SReachTools
#
matlab -nodisplay -nosoftwareopengl -r "setup_dependencies;"
